In [2]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES=True

In [3]:
training_set = tf.keras.utils.image_dataset_from_directory(
    'dataset/images dataset/train',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(256,256),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False
)

Found 60000 files belonging to 5 classes.


In [4]:
validation_set = tf.keras.utils.image_dataset_from_directory(
    'dataset/images dataset/val',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(256,256),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False
)

Found 15000 files belonging to 5 classes.


In [5]:
model = tf.keras.models.Sequential()
# model layers
model.add(tf.keras.layers.Conv2D(filters=32,kernel_size=3,padding='same',activation='relu',input_shape=[256,256,3]))
model.add(tf.keras.layers.Conv2D(filters=32,kernel_size=3,activation='relu'))
model.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2))

model.add(tf.keras.layers.Conv2D(filters=64,kernel_size=3,padding='same',activation='relu'))
model.add(tf.keras.layers.Conv2D(filters=64,kernel_size=3,activation='relu'))
model.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2))

model.add(tf.keras.layers.Conv2D(filters=128,kernel_size=3,padding='same',activation='relu'))
model.add(tf.keras.layers.Conv2D(filters=128,kernel_size=3,activation='relu'))
model.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2))

model.add(tf.keras.layers.Conv2D(filters=256,kernel_size=3,padding='same',activation='relu'))
model.add(tf.keras.layers.Conv2D(filters=256,kernel_size=3,activation='relu'))
model.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2))

model.add(tf.keras.layers.Conv2D(filters=512,kernel_size=3,padding='same',activation='relu'))
model.add(tf.keras.layers.Conv2D(filters=512,kernel_size=3,activation='relu'))
model.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2))

model.add(tf.keras.layers.Dropout(0.25))
#flatten layers
model.add(tf.keras.layers.Flatten())
# hidden layers
model.add(tf.keras.layers.Dense(units=1500,activation='relu'))
model.add(tf.keras.layers.Dropout(0.4))
#output layers
model.add(tf.keras.layers.Dense(units=5,activation='softmax'))

c:\Users\vinay\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [6]:
model.compile(optimizer=tf.keras.optimizers.Adam(
    learning_rate=0.0001),loss='categorical_crossentropy',metrics=['accuracy'])

In [7]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 256, 256, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 254, 254, 32)   │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 127, 127, 32)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 127, 127, 64)   │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 125, 125, 64)   │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 62, 62, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_4 (Conv2D)               │ (None, 62, 62, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_5 (Conv2D)               │ (None, 60, 60, 128)    │       147,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 30, 30, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_6 (Conv2D)               │ (None, 30, 30, 256)    │       295,168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_7 (Conv2D)               │ (None, 28, 28, 256)    │       590,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_3 (MaxPooling2D)  │ (None, 14, 14, 256)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_8 (Conv2D)               │ (None, 14, 14, 512)    │     1,180,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_9 (Conv2D)               │ (None, 12, 12, 512)    │     2,359,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_4 (MaxPooling2D)  │ (None, 6, 6, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 6, 6, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 18432)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1500)           │    27,649,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 1500)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 5)              │         7,505 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 32,369,229 (123.48 MB)

 Trainable params: 32,369,229 (123.48 MB)

 Non-trainable params: 0 (0.00 B)

In [8]:
training_history = model.fit(x=training_set,validation_data=validation_set,epochs=15)

Epoch 1/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5152s 3s/step - accuracy: 0.8894 - loss: 0.4259 - val_accuracy: 0.9681 - val_loss: 0.0960
Epoch 2/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5036s 3s/step - accuracy: 0.9723 - loss: 0.0823 - val_accuracy: 0.9923 - val_loss: 0.0256
Epoch 3/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5068s 3s/step - accuracy: 0.9898 - loss: 0.0318 - val_accuracy: 0.9952 - val_loss: 0.0160
Epoch 4/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5089s 3s/step - accuracy: 0.9941 - loss: 0.0187 - val_accuracy: 0.9944 - val_loss: 0.0201
Epoch 5/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5141s 3s/step - accuracy: 0.9953 - loss: 0.0159 - val_accuracy: 0.9940 - val_loss: 0.0215
Epoch 6/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5140s 3s/step - accuracy: 0.9961 - loss: 0.0135 - val_accuracy: 0.9966 - val_loss: 0.0105
Epoch 7/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5125s 3s/step - accuracy: 0.9959 - loss: 0.0138 - val_accuracy: 0.9963 - val_loss: 0.0126
Epoch 8/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5132s 3s/step - accuracy: 0.9963 -

In [9]:
train_loss, train_acc = model.evaluate(training_set)
print('Training accuracy:', train_acc)

1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1094s 583ms/step - accuracy: 0.9992 - loss: 0.0027
Training accuracy: 0.9994166493415833


In [10]:
val_loss, val_acc = model.evaluate(validation_set)
print('Validation accuracy:', val_acc)

469/469 ━━━━━━━━━━━━━━━━━━━━ 271s 578ms/step - accuracy: 0.9983 - loss: 0.0069
Validation accuracy: 0.9973999857902527


In [11]:
model.save('rice_prediction.keras')

In [12]:
import json
with open('training_hist.json','w') as f:
  json.dump(training_history.history,f)

In [13]:
training_history.history

{'accuracy': [0.9428333044052124,
  0.979366660118103,
  0.9913666844367981,
  0.9946333169937134,
  0.9952999949455261,
  0.9959333539009094,
  0.9964166879653931,
  0.9965166449546814,
  0.9974333047866821,
  0.9973166584968567,
  0.9970999956130981,
  0.9973499774932861,
  0.9975666403770447,
  0.9974333047866821,
  0.99795001745224],
 'loss': [0.17941619455814362,
  0.06234559789299965,
  0.027072031050920486,
  0.017557887360453606,
  0.015562591142952442,
  0.013297240249812603,
  0.01157810352742672,
  0.011212149634957314,
  0.008681190200150013,
  0.0091058649122715,
  0.009214221499860287,
  0.00782690104097128,
  0.007937687449157238,
  0.007538096979260445,
  0.006490023341029882],
 'val_accuracy': [0.9681333303451538,
  0.9923333525657654,
  0.995199978351593,
  0.9944000244140625,
  0.9940000176429749,
  0.9965999722480774,
  0.9962666630744934,
  0.9956666827201843,
  0.9914000034332275,
  0.9974666833877563,
  0.9954666495323181,
  0.9969333410263062,
  0.99713331460952

In [14]:
class_name = validation_set.class_names
print(len(class_name))
class_name

5


['Arborio', 'Basmati', 'Ipsala', 'Jasmine', 'Karacadag']

In [15]:
test_set = tf.keras.utils.image_dataset_from_directory(
    'dataset/images dataset/val',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=1,
    image_size=(256, 256),
    shuffle=False,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False
)

Found 15000 files belonging to 5 classes.


In [16]:
y_pred = model.predict(test_set)
y_pred,y_pred.shape

15000/15000 ━━━━━━━━━━━━━━━━━━━━ 618s 41ms/step


(array([[9.99999881e-01, 1.70106564e-13, 3.00289429e-08, 1.61808000e-09,
         7.50441274e-08],
        [9.99995470e-01, 2.13515886e-10, 4.08559299e-06, 3.57519212e-07,
         1.28720771e-07],
        [9.99998808e-01, 8.12889964e-11, 7.54694938e-08, 9.13467147e-07,
         7.90936241e-08],
        ...,
        [1.04513811e-06, 8.57748317e-11, 5.57115492e-08, 5.31344524e-09,
         9.99998927e-01],
        [1.08395263e-07, 1.08659026e-10, 1.23213848e-08, 2.53353183e-09,
         9.99999881e-01],
        [1.69539813e-08, 3.55610696e-13, 2.19872409e-09, 1.01499260e-11,
         1.00000000e+00]], dtype=float32),
 (15000, 5))

In [17]:
predicated_categories = tf.argmax(y_pred,axis=1)
predicated_categories

<tf.Tensor: shape=(15000,), dtype=int64, numpy=array([0, 0, 0, ..., 4, 4, 4], dtype=int64)>

In [18]:
true_categories = tf.concat([y for x,y in test_set],axis = 0)
true_categories

<tf.Tensor: shape=(15000, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [19]:
y_true = tf.argmax(true_categories,axis = 1)
y_true

<tf.Tensor: shape=(15000,), dtype=int64, numpy=array([0, 0, 0, ..., 4, 4, 4], dtype=int64)>

In [20]:
from sklearn.metrics import classification_report

In [21]:
print(classification_report(y_true,predicated_categories,target_names = class_name))

              precision    recall  f1-score   support

     Arborio       1.00      0.99      1.00      3000
     Basmati       1.00      1.00      1.00      3000
      Ipsala       1.00      1.00      1.00      3000
     Jasmine       0.99      1.00      0.99      3000
   Karacadag       1.00      1.00      1.00      3000

    accuracy                           1.00     15000
   macro avg       1.00      1.00      1.00     15000
weighted avg       1.00      1.00      1.00     15000

